{
  imports = [
    ./catppuccin.nix
    ./fastfetch.nix
    ./git.nix
    ./kitty.nix
    ./neovim.nix
    ./spicetify.nix
    ./starship.nix
    ./yazi.nix
    ./zsh.nix
    ./dunst/dunst.nix
    ./eww/eww.nix
    ./hypr/hypridle.nix
    ./hypr/hyprland.nix
    ./hypr/hyprlock.nix
    ./rofi/rofi.nix
  ];
}
