{
  imports = [
    ./bluetooth.nix
    ./bootloader.nix
    ./env.nix
    ./hyprland.nix
    ./kdeconnect.nix
    ./network.nix
    ./nextcloud.nix
    ./nixvim/nixvim.nix
    ./opentabletdriver.nix
    ./security.nix
    ./services.nix
    ./sound.nix
    ./systemd.nix
    ./thunar.nix
    ./trim.nix
    ./user.nix
    ./virtmanager.nix
    ./xdg-portal.nix
    ./zram.nix
  ];
}
