{
  imports = [
    ./bluetooth.nix
    ./bootloader.nix
    ./env.nix
    ./hyprland.nix
    ./network.nix
    ./nixvim/nixvim.nix
    ./security.nix
    ./services.nix
    ./sound.nix
    ./systemd.nix
    ./thunar.nix
    ./trim.nix
    ./user.nix
    ./virtmanager.nix
    ./xserver.nix
    ./zram.nix
  ];
}
