{ pkgs, ... }:
{
  services = {
    xserver = {
      enable = false;
      xkb = {
        layout = "us";
        variant = "";
      };
    };
  greetd = {
    enable = true;
    vt = 3;
    settings = {
      default_session = {
        # Wayland Desktop Manager is installed only for user ryan via home-manager!
        user = "bathys";
        # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
        # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
        # command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
        command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd Hyprland"; # start Hyprland with a TUI login manager
      };
    };
  };
  smartd = {
    enable = false;
    autodetect = true;
  };
  libinput.enable = true;
  fstrim.enable = true;
  gvfs.enable = true;
  flatpak.enable = false;
  printing = {
    enable = true;
    drivers = [
      # pkgs.hplipWithPlugin
    ];
  };
  gnome.gnome-keyring.enable = true;
  ipp-usb.enable = true;
  syncthing = {
    enable = false;
    user = "bathys";
    dataDir = "/home/bathys";
    configDir = "/home/bathys/.config/syncthing";
  };
  rpcbind.enable = false;
  nfs.server.enable = false;

### Laptop
 # thermald.enable = true;
 # tlp.enable = true;
  logind.extraConfig = ''
    # don’t shutdown when power button is short-pressed
    HandlePowerKey=suspend
  	'';
  };
}
